In [21]:
import numpy as np
x = np.arange(2, 11).reshape(3, 3)
print(x)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [23]:
y = x
print(y)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [12]:
ans=x*5

In [22]:
print("Original matrix\n",x)

print("\nAfter Multiplication\n",ans)

Original matrix
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]

After Multiplication
 [[10 15 20]
 [25 30 35]
 [40 45 50]]


In [25]:
id1 = id(x)
print(id1)

59796584


In [26]:
id2 = id(y)
print(id2)

59796584
